import os
import sys
import torch
import numpy as np
from pathlib import Path

# Add the BigEarthNet.txt directory to sys.path so we can import the datamodule
repo_path = os.path.join(os.path.dirname(__file__), "..", "..", "BigEarthNet.txt")
sys.path.insert(0, os.path.abspath(repo_path))

import rasterio

# pyrefly: ignore [missing-import]
import ben_txt_datamodule
from ben_txt_datamodule import BENTxTDataModule, BENImageReader

# -------------------------------------------------------------------------
# LMDB Monkey-Patch for Mock Environment
# We patch __getitem__ to return real pixels from our fixture image 
# instead of reading actual LMDB safetensors (since we can't build the LMDB without rico-hdl)
# -------------------------------------------------------------------------

def mock_getitem(self, key: str):
    # Load a real sentinel-2 patch
    import hashlib
    # Map sample_id to one of the 100 downloaded real Sentinel-2 patches
    hash_val = int(hashlib.md5(key.encode('utf-8')).hexdigest(), 16) % 100
    fixture_img = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "fixtures", "subset", f"sample_{hash_val}.tif"))
    if not os.path.exists(fixture_img):
        # Fallback to random if fixture missing, but normally we should load the fixture
        return torch.randn(12, 120, 120, dtype=torch.float32)
        
    try:
        with rasterio.open(fixture_img) as src:
            img = src.read() # usually 3 or 4 bands
        
        # We need 12 bands (S1S2-10m20m format) and 120x120 size
        img = img.astype(np.float32)
        
        import torch.nn.functional as F
        
        # img has shape [C, H, W]
        img_t = torch.from_numpy(img).unsqueeze(0) # [1, C, H, W]
        # Resize to 120x120
        resized_t = F.interpolate(img_t, size=(120, 120), mode='bilinear', align_corners=False)
        resized = resized_t.squeeze(0).numpy()
        
        # Pad to 12 bands
        final_img = np.zeros((12, 120, 120), dtype=np.float32)
        bands_to_copy = min(12, img.shape[0])
        final_img[:bands_to_copy] = resized[:bands_to_copy]
        
        # Add some slight variation based on the key so not all patches are identical
        np.random.seed(hash(key) % (2**32))
        noise = np.random.randn(12, 120, 120).astype(np.float32) * 5.0
        final_img += noise
        
        return torch.from_numpy(final_img)
    except Exception as e:
        return torch.randn(12, 120, 120, dtype=torch.float32)

BENImageReader.__getitem__ = mock_getitem

def patch_dataset_getitem():
    from ben_txt_datamodule import BENTxTDataset
    orig_getitem = BENTxTDataset.__getitem__
    def new_getitem(self, idx):
        item = orig_getitem(self, idx)
        if isinstance(item, dict):
            # Try to determine the patch id
            patch_id = ""
            if hasattr(self, "text_data"):
                patch_id = str(self.text_data.iloc[idx].get("patch_id", ""))
            elif hasattr(self, "metadata"):
                patch_id = str(self.metadata.iloc[idx].get("patch_id", ""))
            
            # Map EXACTLY to the fetched STAC subset without modulo hashing
            fixture_img = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "fixtures", "gee_subset", f"{patch_id}.tif"))
            item["source_file_path"] = fixture_img
        return item
    BENTxTDataset.__getitem__ = new_getitem

# Apply patch
patch_dataset_getitem()

def mock_open_env(self):
    self.env = "mock_env"

BENImageReader.open_env = mock_open_env

def get_bigearthnet_datamodule():
    """Initializes and returns the official BENTxTDataModule with stratified subset filtering."""
    
    # Target the real LMDB directory generated by rico-hdl
    encoded_dir = os.path.join(os.path.dirname(__file__), "..", "..", "Encoded-BigEarthNet")
    os.makedirs(encoded_dir, exist_ok=True)
    
    backend_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    metadata_file = os.path.join(backend_dir, "BigEarthNet.txt", "BigEarthNet.txt.parquet")
    
    # If we generated a local geographic subset, use that instead of the 4.6M row parquet
    subset_parquet = os.path.join(backend_dir, "fixtures", "gee_subset", "subset.parquet")
    if os.path.exists(subset_parquet):
        metadata_file = subset_parquet
        
    dm = BENTxTDataModule(
        image_lmdb_file=encoded_dir,
        metadata_file=metadata_file,
        bands="S1S2-10m20m",
        img_size=120,
        batch_size=8,
        num_workers_dataloader=0, # Use 0 in windows/mock to avoid multiprocessing issues
        types=['binary', 'mcq', 'captioning', 'bounding box'],
        categories=None,
        countries=None,
        seasons=None,
        climate_zones=None,
        point_token=['<point>', '</point>'],
        ref_token=['<ref>', '</ref>'],
    )
    
    print("[DataModule] Setting up BENTxTDataModule...")
    dm.setup()
    print("[DataModule] Setup complete.")
    return dm
